### PR TITLE
Fix selfheating

### PR DESCRIPTION
**Pull request by AnHardt**
Shut off bias current after one shot conversion to minimize self heating.
Fixing  #1
Makes some 1/10°C for a 3mm diameter 10mm length cartridge in free not moving air at room temperature when called once per second. (even when called only every 10 seconds a difference is visible) (room thermometer) (it's sensor surface size dependent) (we produce about 1mA at 100 Ohm = 0,0001W = 0.1mW if always on) (if in a metal heater block or a liquid this is negligible, but not in air or less thermal conductive media )

--------

A PR for "auto mode" with the bias current always on but without the busy waiting when waiting for stabilizing the bias current and waiting for the conversion will follow one day.

### CODE REVIEW

**Comment by AnHardt** [comment]
That's all for now.

**Comment by caternuson** [comment]
It appears your 3 recent PRs are cumulative. #28 fixes the NULL pointer issue. #29 does that and fixes typo. This one does all that plus tweaks the heater.

Seem like we can only merge this one take care of all of these?

Did you test this PR, the one with ALL of the changes, also with your UNO?

**Comment by AnHardt** [comment]
Yes they are cumulative, but better separated than my previous #16 what was completely ignored. This way i hope to get a bit more feedback about what you like and what not.

Yes. Tested on UNO and DUE with various of my applications.

**Comment by caternuson** [comment]
Thanks. Cool. Let's merge this one then :)

**Pull request merged**
