### PR TITLE
Enable continuous conversion

### PR DESCRIPTION
**Pull request by budulinek**
Hi all,
This PR implements continuous conversion, according to specs. What I did:

- created flags for storing the configuration (bias voltage, continuous conversion and 50Hz filter)
- changed the readRTD function. In continuous mode there is no need to turn bias to true (bias voltage is on by default in continuous mode), there is no need to write MAX31865_CONFIG_1SHOT to start conversion.

Because we do not need the two delays in continuous mode, enabling the continuous mode through autoConvert(true) is a quick fix to https://github.com/adafruit/Adafruit_MAX31865/issues/10

Of course there are costs. Bias voltage is always on in continous mode (regardless of the enableBias() setting). This can lead to selfheating in the continuous mode.

TODO: Non-blocking "single shot" mode. Working solution is here: https://forum.arduino.cc/index.php?topic=703346.15

### CODE REVIEW

**Comment by sylvanoMTL** [comment]
I have tried this piece of code and unfortunatelly, the RTD values are not changing.
The filter implementation is going well, however there is an issue with the RTD readings continuously. The values are fixed to defined values. Below I have 15 RTDs, RTD#4 and #15 are connected and have defined rtd values of 8631 and 8315. 

15_RTDs_continuous_MAX31865_issue

**Comment by sylvanoMTL** [comment]
My Bad, I have forgot to enable the Bias permanently. The code works perfectly. as long as you use this piece of code in the setup()
```
  for(byte i=0;i<thermo_arrayLen;i++){
    thermo_array[i].begin(MAX31865_4WIRE);   
    thermo_array[i].enable50Hz(true);
    #ifdef CONTINUOUS_MODE
      thermo_array[i].autoConvert(true);
      thermo_array[i].enableBias(true);
          delay(10); //Note 4 datasheet
    #endif
```

**Comment by budulinek** [comment]
Strange. According to datasheet (p. 13):

> When automatic (continuous) conversion mode is selected, VBIAS remains on continuously.

So I thought that in automatic (continuous) mode, VBIAS is always on, regardless of the enableBias() setting.

**Comment by sylvanoMTL** [comment]
> Strange. According to datasheet (p. 13):
> 
> > When automatic (continuous) conversion mode is selected, VBIAS remains on continuously.
> 
> So I thought that in automatic (continuous) mode, VBIAS is always on, regardless of the enableBias() setting.

I agree the datasheet on this aspect is somehow confusing. I think the begin() function should have been modified anyway to reflect the mode. 
Btw well done for this upgrade.

**Comment by budulinek** [comment]
I am closing this pull request (I have made too many changes). For non-blocking library, check my fork.

**Pull request closed without merging**
