### PR TITLE
Add enable50Hz(boolean b) to enable the 50Hz notch filter

### PR DESCRIPTION
**Pull request by newydave**
This adds enable50Hz(boolean b) for countries that use 50Hz.  The power on reset value is 60Hz so those users don't need to change anything, but can use enable50Hz(false) if they wish.

### CODE REVIEW

**Comment by LinoBarreca** [comment]
@newydave change, in your code, boolean to bool.
I already made another PR for this, so they are consistent when they both will be merged.

**Comment by robin-gdwl** [comment]
Hey, this is exactly what I need for my project. Is there a reason why this was never merged?

**Comment by ladyada** [comment]
there's a merge conflict so we couldn't merge it - please try the changes, if they work for you we could manually add it.

**Comment by 22chrs** [comment]
We added the lines in the library and added the function thermistor_1.enable50Hz(true) into our setup. It did not work. We still get the "Fault 0x4 Under/Over voltage".

Connecting GND of the Arduino with the metal frame where the thermistor is mounted, makes the hole thing working. We are unsure if this a good practice, maybe it would be better getting the 50hz filter working?

**Comment by ladyada** [comment]
yay! thanks :)

**Pull request merged**
